SELECT * FROM accounts;
SELECT * FROM subscriptions;
SELECT * FROM feature_usage;
SELECT * FROM churn_events;
SELECT * FROM support_tickets;

--Calculate total MRR and average MRR per plan tier??

SELECT
    plan_tier,
    SUM(mrr_amount) AS total_mrr,
    AVG(mrr_amount) AS average_mrr
FROM subscriptions
GROUP BY plan_tier
ORDER BY total_mrr DESC;

--Identify industries contributing the highest total revenue??

-- Industries contributing the highest total revenue??

SELECT
    a.industry,
    SUM(s.mrr_amount) AS total_revenue
FROM accounts a
JOIN subscriptions s
    ON a.account_id = s.account_id
GROUP BY a.industry
ORDER BY total_revenue DESC;

--Find the top 5 countries by total revenue and their average seat count??

SELECT
    a.country,
    SUM(s.mrr_amount)   AS total_revenue,
    AVG(a.seats)  AS avg_seat_count
FROM accounts a
JOIN subscriptions s
    ON a.account_id = s.account_id
GROUP BY a.country
ORDER BY total_revenue DESC
LIMIT 5;

--Compute churn rate by plan tier??

SELECT
    plan_tier,
    COUNT(*) AS total_accounts,
    SUM(CASE WHEN churn_flag = TRUE THEN 1 ELSE 0 END) AS churned_accounts,
    ROUND(
        SUM(CASE WHEN churn_flag = TRUE THEN 1 ELSE 0 END)::NUMERIC
        / COUNT(*) * 100,
        2
    ) AS churn_rate_percentage
FROM accounts
GROUP BY plan_tier
ORDER BY churn_rate_percentage DESC;

--Compare revenue generated by different referral sources??

SELECT
    a.referral_source,
    SUM(s.mrr_amount) AS total_revenue,
    AVG(s.mrr_amount) AS avg_revenue_per_subscription
FROM accounts a
JOIN subscriptions s
    ON a.account_id = s.account_id
GROUP BY a.referral_source
ORDER BY total_revenue DESC;

--Build a trial-to-paid conversion funnel showing:
--total trial accounts
--converted paid accounts
--conversion rate

-- Trial-to-Paid Conversion Funnel

WITH trial_accounts AS (
    SELECT
        account_id
    FROM accounts
    WHERE is_trial = TRUE
),
paid_conversions AS (
    SELECT DISTINCT
        t.account_id
    FROM trial_accounts t
    JOIN subscriptions s
        ON t.account_id = s.account_id
    WHERE s.mrr_amount > 0
)

SELECT
    COUNT(DISTINCT t.account_id) AS total_trial_accounts,
    COUNT(DISTINCT p.account_id) AS converted_paid_accounts,
    ROUND(
        COUNT(DISTINCT p.account_id)::NUMERIC
        / COUNT(DISTINCT t.account_id) * 100,
        2
    ) AS conversion_rate_percentage
FROM trial_accounts t
LEFT JOIN paid_conversions p
    ON t.account_id = p.account_id;

--Create monthly signup cohorts and calculate churn within 30, 60, and 90 days??

-- Monthly signup cohorts with churn within 30, 60, and 90 days

WITH signup_cohorts AS (
    SELECT
        a.account_id,
        DATE_TRUNC('month', a.signup_date) AS cohort_month,
        a.signup_date
    FROM accounts a
),
churn_data AS (
    SELECT
        ce.account_id,
        ce.churn_date
    FROM churn_events ce
)

SELECT
    sc.cohort_month,
    COUNT(sc.account_id) AS cohort_size,

    COUNT(
        CASE
            WHEN cd.churn_date IS NOT NULL
             AND cd.churn_date <= sc.signup_date + INTERVAL '30 days'
            THEN 1
        END
    ) AS churn_30_days,

    COUNT(
        CASE
            WHEN cd.churn_date IS NOT NULL
             AND cd.churn_date <= sc.signup_date + INTERVAL '60 days'
            THEN 1
        END
    ) AS churn_60_days,

    COUNT(
        CASE
            WHEN cd.churn_date IS NOT NULL
             AND cd.churn_date <= sc.signup_date + INTERVAL '90 days'
            THEN 1
        END
    ) AS churn_90_days

FROM signup_cohorts sc
LEFT JOIN churn_data cd
    ON sc.account_id = cd.account_id
GROUP BY sc.cohort_month
ORDER BY sc.cohort_month;

--For each signup cohort, calculate average revenue generated in the first 3 months??

-- Average revenue generated in the first 3 months for each signup cohort

WITH signup_cohorts AS (
    SELECT
        a.account_id,
        DATE_TRUNC('month', a.signup_date) AS cohort_month,
        a.signup_date
    FROM accounts a
),
revenue_window AS (
    SELECT
        sc.cohort_month,
        s.account_id,
        s.mrr_amount
    FROM signup_cohorts sc
    JOIN subscriptions s
        ON sc.account_id = s.account_id
    WHERE s.start_date <= sc.signup_date + INTERVAL '3 months'
)

SELECT
    cohort_month,
    ROUND(AVG(mrr_amount), 2) AS avg_revenue_first_3_months
FROM revenue_window
GROUP BY cohort_month
ORDER BY cohort_month;

--How many accounts remain active month-over-month based on subscription end dates?

WITH subscription_months AS (
    SELECT
        DATE_TRUNC('month', start_date) AS month_start,
        account_id,
        start_date,
        end_date
    FROM subscriptions
),
calendar_months AS (
    SELECT
        generate_series(
            (SELECT MIN(start_date) FROM subscriptions),
            CURRENT_DATE,
            INTERVAL '1 month'
        )::DATE AS month_start
),
active_accounts AS (
    SELECT DISTINCT
        cm.month_start,
        sm.account_id
    FROM calendar_months cm
    JOIN subscription_months sm
        ON sm.start_date <= cm.month_start
       AND (sm.end_date IS NULL OR sm.end_date >= cm.month_start)
)
SELECT
    month_start,
    COUNT(DISTINCT account_id) AS active_accounts
FROM active_accounts
GROUP BY month_start
ORDER BY month_start;

--What percentage of churned accounts had a downgrade before churn?

WITH churned_accounts AS (
    SELECT DISTINCT
        ce.account_id
    FROM churn_events ce
),
downgraded_before_churn AS (
    SELECT DISTINCT
        ce.account_id
    FROM churn_events ce
    WHERE ce.preceding_downgrade_flag = TRUE
)

SELECT
    COUNT(DISTINCT d.account_id) AS downgraded_churned_accounts,
    COUNT(DISTINCT c.account_id) AS total_churned_accounts,
    ROUND(
        COUNT(DISTINCT d.account_id)::NUMERIC
        / COUNT(DISTINCT c.account_id) * 100,
        2
    ) AS downgrade_before_churn_percentage
FROM churned_accounts c
LEFT JOIN downgraded_before_churn d
    ON c.account_id = d.account_id;


--How much MRR was lost from accounts that downgraded before churning?

WITH downgraded_churn_accounts AS (
    SELECT DISTINCT
        ce.account_id
    FROM churn_events ce
    WHERE ce.preceding_downgrade_flag = TRUE
),
mrr_lost AS (
    SELECT
        s.account_id,
        s.mrr_amount
    FROM subscriptions s
    JOIN downgraded_churn_accounts d
        ON s.account_id = d.account_id
)

SELECT
    SUM(mrr_amount) AS total_mrr_lost,
    ROUND(AVG(mrr_amount), 2) AS avg_mrr_lost_per_account
FROM mrr_lost;

--How many churned accounts were later reactivated, and what is their average MRR after reactivation?

WITH reactivated_accounts AS (
    SELECT DISTINCT
        ce.account_id
    FROM churn_events ce
    WHERE ce.is_reactivation = TRUE
),
reactivated_mrr AS (
    SELECT
        s.account_id,
        s.mrr_amount
    FROM subscriptions s
    JOIN reactivated_accounts r
        ON s.account_id = r.account_id
    WHERE s.mrr_amount > 0
)

SELECT
    COUNT(DISTINCT r.account_id) AS reactivated_account_count,
    ROUND(AVG(rm.mrr_amount), 2) AS avg_mrr_after_reactivation
FROM reactivated_accounts r
LEFT JOIN reactivated_mrr rm
    ON r.account_id = rm.account_id;






